version: "3"

services:

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=aiohttp_user
      - POSTGRES_PASSWORD=aiohttp_pass
      - POSTGRES_DB=aiohttp

  web:
    container_name: aiohttp
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DATABASE=aiohttp
    depends_on:
      - db

volumes:
  postgres_data:
