"""Enum-string

Revision ID: 02a11ba7d361
Revises: 47f2b05da9ac
Create Date: 2021-04-18 18:20:43.203151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a11ba7d361'
down_revision = '47f2b05da9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
