"""Enum

Revision ID: 47f2b05da9ac
Revises: ee588d84c7dc
Create Date: 2021-04-18 17:30:08.178828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f2b05da9ac'
down_revision = 'ee588d84c7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
